### ISSUE TITLE
"OperationalError: could not lock RRD" after upgrading from python3-rrdtool from 1.7.0 to 1.7.2

### ISSUE THREAD

**Issue by ekondrashev** [oetiker/rrdtool-1.x#1228]
**Describe the bug**
Hi RRD Tool Community!

After upgrading of python3-rrdtool from 1.7.0 to 1.7.2 we started seeing below stacktraces during our performance tests cycles
```
May 14 01:54:03 django-admin[544208]: Traceback (most recent call last):
May 14 01:54:03 django-admin[544208]:   File "debian/abc/usr/lib/python3.10/dist-packages/abc/models.py", line 519, in a
May 14 01:54:03 django-admin[544208]:   File "debian/abc/usr/lib/python3.10/dist-packages/abc/results/ts.py", line 55, in update
May 14 01:54:03 django-admin[544208]:   File "debian/abc/usr/lib/python3.10/dist-packages/abc/results/ts.py", line 76, in update_rrd
May 14 01:54:03 django-admin[544208]:   File "debian/abc/usr/lib/python3.10/dist-packages/abc/results/models.py", line 695, in update
May 14 01:54:03 django-admin[544208]:   File "debian/abcn/usr/lib/python3.10/dist-packages/abc/r/rrd.py", line 100, in update
May 14 01:54:03 django-admin[544208]: rrdtool.OperationalError: could not lock RRD
```

in the `rrd.update` we just call
```
rrdtool.update([f] + args)
```
where
```
 f=“rrdfile123”
args=[‘--’, ‘1684025402:468.37027:0.0:0:0.063:0.208:0.652:0.589:0:U:0:U:0:0:38568:0’, ‘1684025403:468.3086:0.0:0:0.061:0.211:0.648:0.587:0:U:0:U:0:0:38563:0’, ‘1684025404:468.33383:0.0:0:0.063:0.21:0.645:0.582:0:U:0:U:0:0:38565:0’, ‘1684025405:468.3455:0.0:0:0.063:0.212:0.657:0.594:0:U:0:U:0:0:38566:0’, ‘1684025406:468.33292:0.0:0:0.064:0.212:0.663:0.599:0:U:0:U:0:0:38565:0’]
```

**To Reproduce**
* call `rrdtool.update` from multiple processes
* * use different filename in each process

I barely can estimate the amount of processes that were calling `rrdtool.update`, but let me state that during test period there were 20000 calls of that method and test started on May 13 18:03:14  and finished on May 14 21:56:06, and there is a limit of having 20 workers at the same time.
I was looking into the logs and can confirm there were no `rrdtool.update` calls done at the same time to the same file.

So the question is whether there were any changes done to the tool that should be taken into consideration?
I was looking into change log file, but found nothing related to that
https://github.com/oetiker/rrdtool-1.x/blob/v1.7.2/CHANGES

Also was trying to analyze the changes itself, but that also gave no much results
https://github.com/oetiker/rrdtool-1.x/compare/v1.7.0..v1.7.2 

**Expected behavior**
No OperationalError occur

**Additional context**

It is important to note that when we where using 1.7.0, it was executed on Ubuntu 18.04 environment, while now 1.7.2 is being used on Ubuntu 22.04.

**Comment by mnalis** [comment]
related https://github.com/oetiker/rrdtool-1.x/issues/1204 ?

**Comment by oetiker** [comment]
### Triage check (master @ 17d1f842)

**Status:** Cannot verify from code alone

The diff between v1.7.0 and v1.7.2 in `src/rrd_open.c` is purely cosmetic (indentation, WIN32 guard cleanup); there is no locking semantic change. The Python binding's global-variable race (`rrdtool_argv`/`rrdtool_argc`) was already fixed before v1.7.0 in commits 3ba510bd and 1361a73d. With `fcntl(F_SETLK, F_WRLCK, l_start=0, l_len=0)`, different files (different inodes) should not contend — which makes the reported "different filename per process" scenario puzzling. A plausible mechanism on 1.7.2 specifically is fd inheritance: `O_CLOEXEC` was only added to `rrd_open()` in commit 6d158d14 (after 1.7.2, PR #1206), so forked worker processes on 1.7.2 could inherit an open+locked fd for a file their sibling/parent already has locked. Also worth noting: the Ubuntu 18.04 → 22.04 switch is a large confounder, and post-1.7.2 PR #1207 added `RRD_LOCKING=block` / `--locking block` (blocking `F_SETLKW`) as a direct fix for exactly this class of "could not lock" failures.

Could you clarify: (a) are the worker processes forked from a parent that opens any RRDs before forking? (b) does setting `RRD_LOCKING=block` in the environment make the errors go away? (c) is upgrading to a newer release (which includes both `O_CLOEXEC` and `--locking block`) an option?
