### ISSUE TITLE
rrdtool dump segfaults

### ISSUE THREAD

**Issue by Quintus** [oetiker/rrdtool-1.x#620]
Hi everyone,

I’m trying to migrate a munin instance from a Raspberry Pi (armv6l) to an x86_64 system. munin uses rrdtool under the hood. Thus I intended to dump the existing RRD files into XML and the restore them on the target machine, but `rrdtool dump` reproducibly always segfaults.

I thus compiled a debug build and made a GDB backtrace for you. Compiling stuff on the RPi takes very long...

Here’s the test run:

~~~~~~~~~~~~~~~~~~
[root@avalon tmp]# /opt/rrdtool-debug/bin/rrdtool --version
RRDtool 1.5.3  Copyright by Tobias Oetiker <tobi@oetiker.ch>
               Compiled May 16 2015 23:58:52

Usage: rrdtool [options] command command_options
Valid commands: create, update, updatev, graph, graphv,  dump, restore,
		last, lastupdate, first, info, fetch, tune
		resize, xport, flushcached

RRDtool is distributed under the Terms of the GNU General
Public License Version 2. (www.gnu.org/copyleft/gpl.html)

For more information read the RRD manpages

[root@avalon tmp]# gdb /opt/rrdtool-debug/bin/rrdtool 
GNU gdb (GDB) 7.9.1
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "armv6l-unknown-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /opt/rrdtool-debug/bin/rrdtool...done.
(gdb) r dump /tmp/data.rrd
Starting program: /opt/rrdtool-debug/bin/rrdtool dump /tmp/data.rrd
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE rrd SYSTEM "http://oss.oetiker.ch/rrdtool/rrdtool.dtd">
<!-- Round Robin Database Dump -->
<rrd>
	<version>0003</version>
	<step>300</step> <!-- Seconds -->

Program received signal SIGSEGV, Segmentation fault.
0xb6f90e98 in fmtstr (str=0xbefff584 "\t<lastupdate>-1225146360</lastupdate> <!-- \266", len=0xbefff4e8, size=256, value=0x538e0fa3 <error: Cannot access memory at address 0x538e0fa3>, width=0, precision=-1, 
    flags=0) at rrd_snprintf.c:984
984		for (strln = 0; value[strln] != '\0' &&
(gdb) bt
#0  0xb6f90e98 in fmtstr (str=0xbefff584 "\t<lastupdate>-1225146360</lastupdate> <!-- \266", len=0xbefff4e8, size=256, value=0x538e0fa3 <error: Cannot access memory at address 0x538e0fa3>, width=0, 
    precision=-1, flags=0) at rrd_snprintf.c:984
#1  0xb6f90adc in rrd_vsnprintf (str=0xbefff584 "\t<lastupdate>-1225146360</lastupdate> <!-- \266", size=256, format=0xb6f9c02e " -->\n\n", args=...) at rrd_snprintf.c:873
#2  0xb6f92778 in rrd_snprintf (str=0xbefff584 "\t<lastupdate>-1225146360</lastupdate> <!-- \266", size=256, format=0xb6f9c008 "\t<lastupdate>%lld</lastupdate> <!-- %s -->\n\n") at rrd_snprintf.c:1575
#3  0xb6f43270 in rrd_dump_cb_r (filename=0xbefffe26 "/tmp/data.rrd", opt_header=1, cb=0xb6f458f0 <rrd_dump_opt_cb_fileout>, user=0xb6f28d58 <_IO_2_1_stdout_>) at rrd_dump.c:142
#4  0xb6f459b8 in rrd_dump_opt_r (filename=0xbefffe26 "/tmp/data.rrd", outname=0x0, opt_noheader=1) at rrd_dump.c:493
#5  0xb6f45dc0 in rrd_dump (argc=2, argv=0xbefffce8) at rrd_dump.c:600
#6  0x000127c4 in HandleInputLine (argc=3, argv=0xbefffce4, out=0xb6f28cb8 <_IO_2_1_stderr_>) at rrd_tool.c:670
#7  0x000120e0 in main (argc=3, argv=0xbefffce4) at rrd_tool.c:545
(gdb) q
A debugging session is active.

	Inferior 1 [process 10355] will be killed.

Quit anyway? (y or n) y
~~~~~~~~~~~~~~~~~~

I uploaded the RRD file used in this example onto my server; find it [here](http://files.quintilianus.eu/misc/data.rrd).

Output of `uname -a`: `Linux avalon.intern 3.18.13-1-ARCH #1 PREEMPT Sun May 10 19:27:21 MDT 2015 armv6l GNU/Linux`. The operating system in use is ArchLinux.

Vale,
Quintus

**Comment by oetiker** [comment]
hmmm this problem only seems to be visible on arm ... is there valgrind on arm ? that might help to figure out where exactly the problem occurs. The negative time looks very odd ...

**Comment by yarda** [comment]
Created pull request #621 which should fix this problem.

The problem is that the reimplementation of vsnprintf is pulling wrong number of bytes from the stack when processing "%lld".

I think it doesn't occur on i686 due to padding.

BTW: I am not sure whether it is good thing to reimplement snprintf/vsnprintf and others. Similar  problems may arise.

**Comment by oetiker** [comment]
Thanks! the reason for the substitution is to have sprintf and sscanf which are NOT locale dependent. Before we used some setlocale magic, which was not boding well with MT environments.
