### ISSUE TITLE
rrdtool graph segfault on invalid (empty) CDEF

### ISSUE THREAD

**Issue by zmousm** [oetiker/rrdtool-1.x#707]
Given a clearly invalid input like this (`aggrf1` and `aggrf2` have no value):

```
rrdtool \
graph \
/tmp/tmpU6HRK1 \
--daemon=unix:/var/run/rrdcached.sock \
--lazy \
-s -1d  \
-e -300  \
-W GRNET \
-t 'Aggregated Traffic for Link agrinio.grnet.gr - mesologgi.grnet.g' \
-v  \
--slope-mode \
-l 0 \
'DEF:d67564057=/srv/www/traffic/agr-mes-1.rrd:ds0:AVERAGE' \
'DEF:d67564057max=/srv/www/traffic/agr-mes-1.rrd:ds0:MAX' \
'CDEF:d67564057dispAVG=d67564057' \
'CDEF:d67564057dispMAX=d67564057' \
'DEF:d67564058=/srv/www/traffic/agr-mes-1.rrd:ds1:AVERAGE' \
'DEF:d67564058max=/srv/www/traffic/agr-mes-1.rrd:ds1:MAX' \
'CDEF:d67564058dispAVG=d67564058' \
'CDEF:d67564058dispMAX=d67564058' \
'CDEF:aggrf1=' \
'CDEF:aggrf2=' \
'COMMENT:              Max\g' \
'COMMENT: Average\g' \
'COMMENT: Current\n' \
'AREA:aggrf1#80f31fbb:In   \:\g' \
'GPRINT:aggrf1:MAX: %7.2lf%s\g' \
'GPRINT:aggrf1:AVERAGE:%7.2lf%s\g' \
'GPRINT:aggrf1:LAST:%7.2lf%s\n' \
LINE2:aggrf2#d5078ebb:Out  \:\g \
'GPRINT:aggrf2:MAX: %7.2lf%s\g' \
'GPRINT:aggrf2:AVERAGE:%7.2lf%s\g' \
'GPRINT:aggrf2:LAST:%7.2lf%s\n'
```

rrdtool 1.5.5 crashes:

```
Program received signal SIGSEGV, Segmentation fault.
rpn_parse (key_hash=key_hash@entry=0x7fffffffc280, expr_const=<optimized out>, lookup=lookup@entry=0x7ffff7ba2980 <find_var_wrapper>) at rrd_rpncalc.c:462
462	rrd_rpncalc.c: No such file or directory.
(gdb) bt
#0  rpn_parse (key_hash=key_hash@entry=0x7fffffffc280, expr_const=<optimized out>, lookup=lookup@entry=0x7ffff7ba2980 <find_var_wrapper>) at rrd_rpncalc.c:462
#1  0x00007ffff7ba5796 in parse_cvdef (gf=gf@entry=GF_CDEF, pa=pa@entry=0x7fffffffc220, im=im@entry=0x7fffffffc280) at rrd_graph_helper.c:989
#2  0x00007ffff7ba76a8 in rrd_graph_script (argc=argc@entry=38, argv=argv@entry=0x7fffffffe2a0, im=im@entry=0x7fffffffc280, optno=<optimized out>) at rrd_graph_helper.c:1528
#3  0x00007ffff7ba2426 in rrd_graph_v (argc=argc@entry=38, argv=argv@entry=0x7fffffffe2a0) at rrd_graph.c:4591
#4  0x00007ffff7ba2643 in rrd_graph (argc=argc@entry=38, argv=argv@entry=0x7fffffffe2a0, prdata=prdata@entry=0x7fffffffdfd8, xsize=xsize@entry=0x7fffffffdfc8, 
    ysize=ysize@entry=0x7fffffffdfd0, stream=stream@entry=0x0, ymin=ymin@entry=0x7fffffffdfe0, ymax=ymax@entry=0x7fffffffdfe8) at rrd_graph.c:4493
#5  0x0000000000402e7f in HandleInputLine (argc=argc@entry=39, argv=argv@entry=0x7fffffffe298, out=0x7ffff7b7f880) at rrd_tool.c:770
#6  0x00000000004016fc in main (argc=39, argv=0x7fffffffe298) at rrd_tool.c:545
```
I found an old issue (#51) that appears to refer to the same thing but I don't know if and how that fix was carried over.

I'm sorry if I'm missing something obvious. Please advise.

**Comment by oetiker** [comment]
it was just a bug :) you did not miss anything ... you found one :)
