### ISSUE TITLE
segfault in print_calc (GFVRULE)

### ISSUE THREAD

**Issue by NHellFire** [oetiker/rrdtool-1.x#859]
I've started getting a lot of crashes when graphing in munin.

Seems at least partly related to #99 (vidx = -1). Full backtrace is attached
```
Core was generated by `/usr/bin/perl /usr/share/munin/munin-graph'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f50ef2d68bf in print_calc (im=im@entry=0x7ffe3a08c1a0) at rrd_graph.c:2025
#0  0x00007f50ef2d68bf in print_calc (im=im@entry=0x7ffe3a08c1a0) at rrd_graph.c:2025
        i = 86
        ii = <optimized out>
        validsteps = <optimized out>
        printval = 108.81183687226154
        tmvdef = {tm_sec = 15, tm_min = 10, tm_hour = 16, tm_mday = 3, tm_mon = 0, tm_year = 118, tm_wday = 3, tm_yday = 2, tm_isdst = 0, tm_gmtoff = 0, tm_zone = 0x55d48b04b880 "GMT"}
        graphelement = <optimized out>
        vidx = -1
        max_ii = <optimized out>
        magfact = -1
        si_symb = 0x7f50ef3044c4 ""
        percent_s = <optimized out>
        prline_cnt = 0
        now = 1514995815
```

Command being used is:
```
rrdtool 'graph' '/var/cache/munin/www/localhost/localhost/cpu-day.png' \
        '--title' \
        'CPU usage - by day' \
        '--start' \
        '-2000m' \
        '--base' \
        '1000' \
        '-r' \
        '--lower-limit' \
        '0' \
        '--upper-limit' \
        '800' \
        '--vertical-label' \
        '%' \
        '--slope-mode' \
        '--height' \
        '175' \
        '--width' \
        '400' \
        '--imgformat' \
        'PNG' \
        '--lazy' \
        '--units-exponent' \
        '0' \
        '--font' \
        'DEFAULT:0:DejaVuSans,DejaVu Sans,DejaVu LGC Sans,Bitstream Vera Sans' \
        '--font' \
        'LEGEND:7:DejaVuSansMono,DejaVu Sans Mono,DejaVu LGC Sans Mono,Bitstream Vera Sans Mono,monospace' \
        '--color' \
        'BACK#F0F0F0' \
        '--color' \
        'FRAME#F0F0F0' \
        '--color' \
        'CANVAS#FFFFFF' \
        '--color' \
        'FONT#666666' \
        '--color' \
        'AXIS#CFD6F8' \
        '--color' \
        'ARROW#CFD6F8' \
        '--border' \
        '0' \
        '-W' \
        'Munin 2.0.33-1' \
        'DEF:aguest=/var/lib/munin/localhost/localhost-cpu-guest-d.rrd:42:MAX' \
        'DEF:iguest=/var/lib/munin/localhost/localhost-cpu-guest-d.rrd:42:MIN' \
        'DEF:gguest=/var/lib/munin/localhost/localhost-cpu-guest-d.rrd:42:AVERAGE' \
        'DEF:asteal=/var/lib/munin/localhost/localhost-cpu-steal-d.rrd:42:MAX' \
        'DEF:isteal=/var/lib/munin/localhost/localhost-cpu-steal-d.rrd:42:MIN' \
        'DEF:gsteal=/var/lib/munin/localhost/localhost-cpu-steal-d.rrd:42:AVERAGE' \
        'DEF:asoftirq=/var/lib/munin/localhost/localhost-cpu-softirq-d.rrd:42:MAX' \
        'DEF:isoftirq=/var/lib/munin/localhost/localhost-cpu-softirq-d.rrd:42:MIN' \
        'DEF:gsoftirq=/var/lib/munin/localhost/localhost-cpu-softirq-d.rrd:42:AVERAGE' \
        'DEF:airq=/var/lib/munin/localhost/localhost-cpu-irq-d.rrd:42:MAX' \
        'DEF:iirq=/var/lib/munin/localhost/localhost-cpu-irq-d.rrd:42:MIN' \
        'DEF:girq=/var/lib/munin/localhost/localhost-cpu-irq-d.rrd:42:AVERAGE' \
        'DEF:aiowait=/var/lib/munin/localhost/localhost-cpu-iowait-d.rrd:42:MAX' \
        'DEF:iiowait=/var/lib/munin/localhost/localhost-cpu-iowait-d.rrd:42:MIN' \
        'DEF:giowait=/var/lib/munin/localhost/localhost-cpu-iowait-d.rrd:42:AVERAGE' \
        'DEF:aidle=/var/lib/munin/localhost/localhost-cpu-idle-d.rrd:42:MAX' \
        'DEF:iidle=/var/lib/munin/localhost/localhost-cpu-idle-d.rrd:42:MIN' \
        'DEF:gidle=/var/lib/munin/localhost/localhost-cpu-idle-d.rrd:42:AVERAGE' \
        'DEF:anice=/var/lib/munin/localhost/localhost-cpu-nice-d.rrd:42:MAX' \
        'DEF:inice=/var/lib/munin/localhost/localhost-cpu-nice-d.rrd:42:MIN' \
        'DEF:gnice=/var/lib/munin/localhost/localhost-cpu-nice-d.rrd:42:AVERAGE' \
        'DEF:auser=/var/lib/munin/localhost/localhost-cpu-user-d.rrd:42:MAX' \
        'DEF:iuser=/var/lib/munin/localhost/localhost-cpu-user-d.rrd:42:MIN' \
        'DEF:guser=/var/lib/munin/localhost/localhost-cpu-user-d.rrd:42:AVERAGE' \
        'DEF:asystem=/var/lib/munin/localhost/localhost-cpu-system-d.rrd:42:MAX' \
        'DEF:isystem=/var/lib/munin/localhost/localhost-cpu-system-d.rrd:42:MIN' \
        'DEF:gsystem=/var/lib/munin/localhost/localhost-cpu-system-d.rrd:42:AVERAGE' \
        'CDEF:csystem=gsystem,POP,UNKN' \
        'COMMENT:       ' \
        'COMMENT: Cur\:' \
        'COMMENT:Min\:' \
        'COMMENT:Avg\:' \
        'COMMENT:Max\:  \j' \
        'AREA:gsystem#00CC00:system  ' \
        'GPRINT:csystem:LAST:%6.2lf' \
        'GPRINT:isystem:MIN:%6.2lf' \
        'GPRINT:gsystem:AVERAGE:%6.2lf' \
        'GPRINT:asystem:MAX:%6.2lf\j' \
        'CDEF:cuser=guser,POP,UNKN' \
        'STACK:guser#0066B3:user    ' \
        'GPRINT:cuser:LAST:%6.2lf' \
        'GPRINT:iuser:MIN:%6.2lf' \
        'GPRINT:guser:AVERAGE:%6.2lf' \
        'GPRINT:auser:MAX:%6.2lf\j' \
        'CDEF:cnice=gnice,POP,UNKN' \
        'STACK:gnice#FF8000:nice    ' \
        'GPRINT:cnice:LAST:%6.2lf' \
        'GPRINT:inice:MIN:%6.2lf' \
        'GPRINT:gnice:AVERAGE:%6.2lf' \
        'GPRINT:anice:MAX:%6.2lf\j' \
        'CDEF:cidle=gidle,POP,UNKN' \
        'STACK:gidle#FFCC00:idle    ' \
        'GPRINT:cidle:LAST:%6.2lf' \
        'GPRINT:iidle:MIN:%6.2lf' \
        'GPRINT:gidle:AVERAGE:%6.2lf' \
        'GPRINT:aidle:MAX:%6.2lf\j' \
        'CDEF:ciowait=giowait,POP,UNKN' \
        'STACK:giowait#330099:iowait  ' \
        'GPRINT:ciowait:LAST:%6.2lf' \
        'GPRINT:iiowait:MIN:%6.2lf' \
        'GPRINT:giowait:AVERAGE:%6.2lf' \
        'GPRINT:aiowait:MAX:%6.2lf\j' \
        'CDEF:cirq=girq,POP,UNKN' \
        'STACK:girq#990099:irq     ' \
        'GPRINT:cirq:LAST:%6.2lf' \
        'GPRINT:iirq:MIN:%6.2lf' \
        'GPRINT:girq:AVERAGE:%6.2lf' \
        'GPRINT:airq:MAX:%6.2lf\j' \
        'CDEF:csoftirq=gsoftirq,POP,UNKN' \
        'STACK:gsoftirq#CCFF00:softirq ' \
        'GPRINT:csoftirq:LAST:%6.2lf' \
        'GPRINT:isoftirq:MIN:%6.2lf' \
        'GPRINT:gsoftirq:AVERAGE:%6.2lf' \
        'GPRINT:asoftirq:MAX:%6.2lf\j' \
        'CDEF:csteal=gsteal,POP,UNKN' \
        'STACK:gsteal#FF0000:steal   ' \
        'GPRINT:csteal:LAST:%6.2lf' \
        'GPRINT:isteal:MIN:%6.2lf' \
        'GPRINT:gsteal:AVERAGE:%6.2lf' \
        'GPRINT:asteal:MAX:%6.2lf\j' \
        'CDEF:cguest=gguest,POP,UNKN' \
        'STACK:gguest#808080:guest   ' \
        'GPRINT:cguest:LAST:%6.2lf' \
        'GPRINT:iguest:MIN:%6.2lf' \
        'GPRINT:gguest:AVERAGE:%6.2lf' \
        'GPRINT:aguest:MAX:%6.2lf\j' \
        'VRULE:0#999999' \
        'COMMENT:Last update\: Thu Jan  1 01\:00\:00 1970\r' \
        '--end' \
        '1515034200'
```

Backtrace is from v1.6.0, but v1.7.0 also produces the same result. Host is Ubuntu 17.10 amd64, munin 2.0.33
[backtrace.txt](https://github.com/oetiker/rrdtool-1.x/files/1602306/backtrace.txt)

**Comment by oetiker** [comment]
### Triage check (master @ 17d1f842)

**Status:** Likely fixed

The segfault was triggered by `VRULE:0#999999` — a VRULE with Unix timestamp 0 — because `xrule == 0` was also the sentinel for "unset", causing `print_calc()` to access `im->gdes[vidx].vf.when` with `vidx == -1` (an out-of-bounds array dereference). Commit `254e4e44` ("Fix double meaning of time 0 as uninitialized value", merged 2020, present since v1.8.x) specifically addresses this by treating `VRULE:0` as `VRULE:1` at parse time. The current parser in `rrd_graph_helper.c` at line 1029–1032 contains that guard, so the reported crash path no longer exists in master. Users on v1.6.0 or v1.7.0 should upgrade to v1.8.0 or later.

**Comment by oetiker** [comment]
Closing during triage — see the triage analysis above for the specific commit(s) that addressed this. Please reopen with current reproduction steps if you can still reproduce this on rrdtool 1.10.x or current master.
